/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opengles_project_GLRender */

#ifndef _Included_com_example_opengles_project_GLRender
#define _Included_com_example_opengles_project_GLRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opengles_project_GLRender
 * Method:    n_initGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_1project_GLRender_n_1initGL
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opengles_project_GLRender
 * Method:    n_drawGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_1project_GLRender_n_1drawGL
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opengles_project_GLRender
 * Method:    n_changeSizeGL
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_1project_GLRender_n_1changeSizeGL
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
